name: data_type_convert_util
description: 数据类型转换工具类
version: 0.0.1
author: wizz.xu
homepage: https://github.com/AerialLadder/data_type_convert_util

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.9.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


